baseURL = 'https://hotissue.rotcha.kr/'
languageCode = 'ko-kr'
title = '1ë¶„ì „ ìƒì„±'
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  env = "production"
  description = "ìƒí™œì— í¸ë¦¬í•¨ì„ ì£¼ëŠ” ë‹¤ì–‘í•œ ì •ë³´ë¥¼ ëª¨ì•˜ìŠµë‹ˆë‹¤."
  author = "1ë¶„ ì •ë³´"

  ShowRelatedContent = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "1ë¶„ì „ ìƒì„±ğŸ‘‹"
    Content = "ë‹¹ì‹ ì˜ ìƒí™œì— í¸ë¦¬í•¨ì„ ë”í•´ ì£¼ëŠ” 1ë¶„ì „ ìƒì„± ì •ë³´ì…ë‹ˆë‹¤."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hugh79757-cmyk"

  [params.cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "í¬ìŠ¤íŠ¸"
    url = "/archives/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "ì†Œê°œ"
    url = "/about/"
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
